"""Create registry tables

Revision ID: 3deddf65580e
Revises: 98b28a73896d
Create Date: 2025-12-19 15:37:49.226923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3deddf65580e'
down_revision: Union[str, Sequence[str], None] = '98b28a73896d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llms',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('size_type', sa.String(), nullable=False),
    sa.Column('billion_params_count', sa.Integer(), nullable=False),
    sa.Column('context_window_tokens', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('capabilities', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('target_domains', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('min_system_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_system_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tariff_method', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_ratings',
    sa.Column('llm_id', sa.Uuid(), nullable=False),
    sa.Column('count_of_usage', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llm_id'], ['llms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('llm_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_ratings')
    op.drop_table('llms')
    # ### end Alembic commands ###
